
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fernando Gonzalez
 */
public class AgregarPacientes extends javax.swing.JDialog {

    /**
     * Creates new form AgregarPacientes
     */
    public AgregarPacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ImageIcon icono = new ImageIcon(getClass().getResource("imagenes\\icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarPacientes();
        TFClave.setEnabled(false);
    }

    public void MostrarPacientes() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarPacientes(TablaPacientes);
        cnx.cerrarConexiones();
    }

    public void Limpiar() {
        TFEdad.setText("");
        TFNombre.setText("");
        TFNacimiento.setText("");
        TFDireccion.setText("");
        TFTelefonoCel.setText("");
        TFTelefono.setText("");
        TFCurp.setText("");
        TFCiudad.setText("");
        TFEmail.setText("");
        TFRFC.setText("");
    }

    public boolean verificarCamposVacios() {
        return TFEdad.getText().isEmpty()
                && TFNombre.getText().isEmpty()
                && TFNacimiento.getText().isEmpty()
                && TFDireccion.getText().isEmpty()
                && TFTelefonoCel.getText().isEmpty()
                && TFTelefono.getText().isEmpty()
                && TFCurp.getText().isEmpty()
                && TFCiudad.getText().isEmpty()
                && TFEmail.getText().isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPacientes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TFEdad = new javax.swing.JTextField();
        TFTelefono = new javax.swing.JTextField();
        TFCiudad = new javax.swing.JTextField();
        TFEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFDireccion = new javax.swing.JTextField();
        TFTelefonoCel = new javax.swing.JTextField();
        TFCurp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BNuevo = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        TFBuscador = new org.jdesktop.swingx.JXSearchField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CBSexo = new javax.swing.JComboBox<>();
        TFRFC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TFNacimiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Pacientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPacientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave:", "Nombre:", "RFC", "Dirección:", "Celular:", "Télefono:", "Curp", "Ciudad", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaPacientes.setRowHeight(25);
        TablaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaPacientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 920, 220));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 26));

        TFNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 440, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Edad:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 26));

        TFEdad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEdadActionPerformed(evt);
            }
        });
        TFEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEdadKeyTyped(evt);
            }
        });
        getContentPane().add(TFEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 300, -1));

        TFTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTelefonoActionPerformed(evt);
            }
        });
        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(TFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 300, -1));

        TFCiudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(TFCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 300, -1));

        TFEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmailActionPerformed(evt);
            }
        });
        TFEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFEmailKeyTyped(evt);
            }
        });
        getContentPane().add(TFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 300, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, 26));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ciudad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, 26));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 26));

        TFDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(TFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 440, -1));

        TFTelefonoCel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFTelefonoCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTelefonoCelActionPerformed(evt);
            }
        });
        TFTelefonoCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoCelKeyTyped(evt);
            }
        });
        getContentPane().add(TFTelefonoCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 440, -1));

        TFCurp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCurpActionPerformed(evt);
            }
        });
        TFCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFCurpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFCurpKeyTyped(evt);
            }
        });
        getContentPane().add(TFCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 440, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CURP:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 26));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telefono Cel:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 26));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dirección:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 26));

        BNuevo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.gif"))); // NOI18N
        BNuevo.setText("Nuevo");
        BNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 132, 36));

        BModificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BModificar.setText("Modificar");
        BModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 132, 36));

        BEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar.setText("Eiminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 132, 36));

        BCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar1.png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 132, 36));

        TFBuscador.setText("");
        TFBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBuscadorActionPerformed(evt);
            }
        });
        getContentPane().add(TFBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 410, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sexo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 26));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("RFC:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 26));

        CBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(CBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 440, -1));

        TFRFC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRFCActionPerformed(evt);
            }
        });
        TFRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFRFCKeyTyped(evt);
            }
        });
        getContentPane().add(TFRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 440, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nacimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, 26));

        TFNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNacimientoActionPerformed(evt);
            }
        });
        TFNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFNacimientoKeyTyped(evt);
            }
        });
        getContentPane().add(TFNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio23.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 590));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio23.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, -4, 210, 560));
        getContentPane().add(TFClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPacientesMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.buscarPacientes(TablaPacientes, TFClave, TFNombre,CBSexo, TFEdad, TFNacimiento, TFRFC, TFDireccion, TFTelefonoCel, TFTelefono, TFCurp, TFCiudad, TFEmail);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TablaPacientesMouseClicked

    private void TFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreActionPerformed
        TFEdad.requestFocus();
    }//GEN-LAST:event_TFNombreActionPerformed

    private void TFEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEdadActionPerformed
        TFRFC.requestFocus();
    }//GEN-LAST:event_TFEdadActionPerformed

    private void TFEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEdadKeyTyped
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter)) {
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
        if (TFEdad.getText().length() >= 13) {
            JOptionPane.showMessageDialog(this, "Ingrese un RFC correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFEdadKeyTyped

    private void TFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTelefonoActionPerformed
        TFDireccion.requestFocus();
    }//GEN-LAST:event_TFTelefonoActionPerformed

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (TFTelefono.getText().length() >= 10) {
            JOptionPane.showMessageDialog(this, "Ingrese su numero telefonico correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void TFCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCiudadActionPerformed
        TFTelefonoCel.requestFocus();
    }//GEN-LAST:event_TFCiudadActionPerformed

    private void TFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmailActionPerformed
        TFCurp.requestFocus();
    }//GEN-LAST:event_TFEmailActionPerformed

    private void TFEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEmailKeyPressed

    }//GEN-LAST:event_TFEmailKeyPressed

    private void TFEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmailKeyTyped

    private void TFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDireccionActionPerformed
        TFCiudad.requestFocus();
    }//GEN-LAST:event_TFDireccionActionPerformed

    private void TFTelefonoCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTelefonoCelActionPerformed
        TFEmail.requestFocus();
    }//GEN-LAST:event_TFTelefonoCelActionPerformed

    private void TFTelefonoCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoCelKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (TFTelefonoCel.getText().length() >= 10) {
            JOptionPane.showMessageDialog(this, "Ingrese su numero telefonico correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFTelefonoCelKeyTyped

    private void TFCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCurpActionPerformed

    }//GEN-LAST:event_TFCurpActionPerformed

    private void TFCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCurpKeyTyped
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter)) {
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
        if (TFCurp.getText().length() >= 18) {
            JOptionPane.showMessageDialog(this, "Ingrese una CURP correcta");
            evt.consume();
        }
    }//GEN-LAST:event_TFCurpKeyTyped

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        if (TFEdad.getText().isEmpty()
                || TFNombre.getText().isEmpty()
                || TFNacimiento.getText().isEmpty()
                || TFDireccion.getText().isEmpty()
                || TFTelefonoCel.getText().isEmpty()
                || TFTelefono.getText().isEmpty()
                || TFCurp.getText().isEmpty()
                || TFCiudad.getText().isEmpty()
                || TFEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llene los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de guardar el registro?");
            if (respuesta == JOptionPane.YES_OPTION) {
                ConexionBDV cnx = new ConexionBDV();
                String Nombre = TFNombre.getText();
                String Edad = TFEdad.getText();
                String Nacimiento = TFNacimiento.getText();
                String Sexo = CBSexo.getSelectedItem().toString();
                String RFC = TFRFC.getText();
                String Direccion = TFDireccion.getText();
                String TelefonoCel = TFTelefonoCel.getText();
                String Telefono = TFTelefono.getText();
                String Curp = TFCurp.getText();
                String Ciudad = TFCiudad.getText();
                String Email = TFEmail.getText();

                String consulta = "INSERT INTO TPacientes "
                        + "VALUES (null,'" + Nombre + "',"
                        + "'" + Edad + "',"
                        + "'" + Sexo + "',"
                        + "'" + Nacimiento + "',"
                        + "'" + RFC + "',"
                        + "'" + Direccion + "',"
                        + "'" + TelefonoCel + "',"
                        + "'" + Telefono + "',"
                        + "'" + Curp + "',"
                        + "'" + Ciudad + "',"
                        + "'" + Email + "')";
                System.out.println(consulta);
                cnx.ejecutarConsultas(consulta);
                Limpiar();
                BModificar.setEnabled(true);
                cnx.mostrarPacientes(TablaPacientes);
                cnx.cerrarConexiones();

            }
        }
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        String Clave1 = TFClave.getText();

        if (Clave1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un paciente antes");
        } else {

            int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de MODIFICAR el registro?");
            if (respuesta == JOptionPane.YES_OPTION) {
                ConexionBDV cnx = new ConexionBDV();
                String Clave = TFClave.getText();
                String RFC = TFEdad.getText();
                String Nombre = TFNombre.getText();
                String Edad = TFEdad.getText();
                String Nacimiento = TFNacimiento.getText();
                String Sexo = CBSexo.getSelectedItem().toString();
                String Direccion = TFDireccion.getText();
                String TelefonoCel = TFTelefonoCel.getText();
                String Telefono = TFTelefono.getText();
                String Curp = TFCurp.getText();
                String Ciudad = TFCiudad.getText();
                String Email = TFEmail.getText();

                String consulta = "UPDATE TPacientes "
                        + "SET Nombre = '" + Nombre + "', "
                        + "Edad = '" + Edad + "', "
                        + "Sexo = '" + Sexo + "', "
                        + "FechaNac = '" + Nacimiento + "', "
                        + "RFC = '" + RFC + "', "
                        + "Direccion = '" + Direccion + "', "
                        + "TelefonoCel = '" + TelefonoCel + "', "
                        + "Telefono = '" + Telefono + "', "
                        + "Curp = '" + Curp + "', "
                        + "Ciudad = '" + Ciudad + "', "
                        + "Email = '" + Email + "' "
                        + "WHERE NoPaciente = " + Clave;
                System.out.println(consulta);
                cnx.ejecutarConsultas(consulta);
                cnx.mostrarPacientes(TablaPacientes);
                Limpiar();
                BModificar.setEnabled(true);
                cnx.cerrarConexiones();

            }
        }
    }//GEN-LAST:event_BModificarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        String Clave1 = TFClave.getText();

        if (Clave1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un paciente antes");
        } else {
            ConexionBDV cnx = new ConexionBDV();
            cnx.borrarPacientes(TFClave.getText());
            cnx.mostrarPacientes(TablaPacientes);
            Limpiar();
            cnx.cerrarConexiones();
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        Limpiar();

    }//GEN-LAST:event_BCancelarActionPerformed

    private void TFBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBuscadorActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarDatosParaPacientesBuscador(TablaPacientes, TFBuscador);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TFBuscadorActionPerformed

    private void TFRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRFCActionPerformed
        TFNacimiento.requestFocus();
    }//GEN-LAST:event_TFRFCActionPerformed

    private void TFNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNacimientoActionPerformed
        CBSexo.requestFocus();
    }//GEN-LAST:event_TFNacimientoActionPerformed

    private void TFNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNacimientoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNacimientoKeyTyped

    private void TFRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFRFCKeyTyped
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter)) {
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
        if (TFRFC.getText().length() >= 13) {
            JOptionPane.showMessageDialog(this, "Ingrese un RFC correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFRFCKeyTyped

    private void TFCurpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCurpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BNuevo.doClick();
        }
    }//GEN-LAST:event_TFCurpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPacientes dialog = new AgregarPacientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JComboBox<String> CBSexo;
    private org.jdesktop.swingx.JXSearchField TFBuscador;
    private javax.swing.JTextField TFCiudad;
    private javax.swing.JTextField TFClave;
    private javax.swing.JTextField TFCurp;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFEdad;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFNacimiento;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFRFC;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFTelefonoCel;
    private javax.swing.JTable TablaPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
