
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ConsultasAdmin extends javax.swing.JDialog {

    /**
     * Creates new form ConsultasAdmin
     */
    public ConsultasAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ImageIcon icono = new ImageIcon(getClass().getResource("imagenes\\icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        MostrarCita();
        TFClave.setEnabled(false);
        ConexionBDV cnx = new ConexionBDV();
    }

    public void MostrarCita() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarCitas(TPrincipal);
        cnx.cerrarConexiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPrincipal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TFClave = new javax.swing.JTextField();
        TFNoPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Examenes");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, 250));

        BEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar.setText("Eiminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminarMouseClicked(evt);
            }
        });
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 125, -1));

        TPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        TPrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        TPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "NoPaciente", "Nombre", "Telefono", "Hora", "Fecha", "Estado", "Resultados", "Realizar Examen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TPrincipal.setRowHeight(25);
        TPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TPrincipal);
        if (TPrincipal.getColumnModel().getColumnCount() > 0) {
            TPrincipal.getColumnModel().getColumn(1).setMinWidth(0);
            TPrincipal.getColumnModel().getColumn(1).setPreferredWidth(0);
            TPrincipal.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 690, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio23.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 720, 390));

        TFClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFClaveActionPerformed(evt);
            }
        });
        getContentPane().add(TFClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 40, 30));

        TFNoPaciente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFNoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(TFNoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFClaveActionPerformed

    private void BEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseClicked
      ConexionBDV cnx = new ConexionBDV();
        String Clave = TFNoPaciente.getText();
        cnx.borrarResultadosParam(Clave);
        cnx.borrarCitaExamen(Clave);
        cnx.borrarCitas(TFClave.getText());
        MostrarCita();
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminarMouseClicked

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.borrarCitas(TFClave.getText());
        MostrarCita();
        //  cnx.verPizzas(TPizzas);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminarActionPerformed

    private void TPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPrincipalMouseClicked
        ConexionBDV cnx = new ConexionBDV();
         int fila_seleccionada = TPrincipal.getSelectedRow();
        TFNoPaciente.setText(TPrincipal.getValueAt(fila_seleccionada, 1).toString());
        cnx.buscarCita(TPrincipal, TFClave);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TPrincipalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int fila_seleccionada = TPrincipal.getSelectedRow();

        if (fila_seleccionada != -1) { 
        ConsultaExamenes fme = new ConsultaExamenes(null, true,
                TPrincipal.getValueAt(fila_seleccionada, 2).toString(),
                TPrincipal.getValueAt(fila_seleccionada, 5).toString());

        this.dispose();
        fme.setVisible(true);
        } else { 
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un paciente", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void TFNoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultasAdmin dialog = new ConsultasAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminar;
    private javax.swing.JTextField TFClave;
    private javax.swing.JTextField TFNoPaciente;
    private javax.swing.JTable TPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
