
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fernando Gonzalez
 */
public class Consultas extends javax.swing.JDialog {

    /**
     * Creates new form Consultas
     */
    public Consultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ImageIcon icono = new ImageIcon(getClass().getResource("imagenes\\icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        MostrarCita();
        TFClave.setEnabled(false);
    }

    public void MostrarCita() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarCitas(TPrincipal);
        cnx.cerrarConexiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPrincipal = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BEliminar1 = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BEstado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TFClave = new javax.swing.JTextField();
        TFNoPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas Quimico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Examenes");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, 250));

        TPrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "NoPaciente", "Nombre", "Telefono", "Hora", "Fecha", "Analisis Realizados", "Resultados", "Examen a realizar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TPrincipal.setRowHeight(25);
        TPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TPrincipal);
        if (TPrincipal.getColumnModel().getColumnCount() > 0) {
            TPrincipal.getColumnModel().getColumn(1).setMinWidth(0);
            TPrincipal.getColumnModel().getColumn(1).setPreferredWidth(0);
            TPrincipal.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 720, 270));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 400));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 610, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BEliminar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        BEliminar1.setText("Agregar Resultado");
        BEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminar1MouseClicked(evt);
            }
        });
        BEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminar1ActionPerformed(evt);
            }
        });

        BEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar.setText("Eiminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminarMouseClicked(evt);
            }
        });
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        BEstado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agendar.png"))); // NOI18N
        BEstado.setText("Estado de los analisis");
        BEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEstadoMouseClicked(evt);
            }
        });
        BEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BEstado)
                .addGap(26, 26, 26)
                .addComponent(BEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BEliminar1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 610, 280));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        TFClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFClaveActionPerformed(evt);
            }
        });
        getContentPane().add(TFClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TFNoPaciente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFNoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(TFNoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPrincipalMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        int fila_seleccionada = TPrincipal.getSelectedRow();
        TFNoPaciente.setText(TPrincipal.getValueAt(fila_seleccionada, 1).toString());
        cnx.buscarCita(TPrincipal, TFClave);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TPrincipalMouseClicked

    private void TFClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFClaveActionPerformed

    private void BEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEstadoMouseClicked

        int fila_seleccionada = TPrincipal.getSelectedRow();
        ModificarConsulta fme = new ModificarConsulta(null, true,
                TPrincipal.getValueAt(fila_seleccionada, 0).toString(),
                TPrincipal.getValueAt(fila_seleccionada, 2).toString(),
                TPrincipal.getValueAt(fila_seleccionada, 5).toString());

        this.dispose();
        fme.setVisible(true);


    }//GEN-LAST:event_BEstadoMouseClicked

    private void BEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEstadoActionPerformed

    private void BEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        String Clave = TFNoPaciente.getText();
        cnx.borrarResultadosParam(Clave);
        cnx.borrarCitaExamen(Clave);
        cnx.borrarCitas(TFClave.getText());
        MostrarCita();
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminarMouseClicked

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int fila_seleccionada = TPrincipal.getSelectedRow();

        if (fila_seleccionada != -1) {
            ConsultaExamenes fme = new ConsultaExamenes(null, true,
                    TPrincipal.getValueAt(fila_seleccionada, 2).toString(),
                    TPrincipal.getValueAt(fila_seleccionada, 5).toString());

            this.dispose();
            fme.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un paciente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void BEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminar1MouseClicked
        String Clave = TFNoPaciente.getText();
        if (Clave.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un paciente antes");
        } else {
            int fila_seleccionada = TPrincipal.getSelectedRow();
            Resultados fme = new Resultados(null, true,
                    TPrincipal.getValueAt(fila_seleccionada, 2).toString(),
                    TPrincipal.getValueAt(fila_seleccionada, 5).toString());

            this.dispose();
            fme.setVisible(true);
        }
    }//GEN-LAST:event_BEliminar1MouseClicked

    private void BEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEliminar1ActionPerformed

    private void TFNoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consultas dialog = new Consultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BEliminar1;
    private javax.swing.JButton BEstado;
    private javax.swing.JTextField TFClave;
    private javax.swing.JTextField TFNoPaciente;
    private javax.swing.JTable TPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
