
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fernando Gonzalez
 */
public class Medicos extends javax.swing.JDialog {

    /**
     * Creates new form Medicos
     */
    public Medicos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ImageIcon icono = new ImageIcon(getClass().getResource("imagenes\\icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        MostrarMedicos();
        TFClave.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    public void MostrarMedicos() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarMedicos(TablaMedico);
        cnx.cerrarConexiones();
    }

    public void limpiar() {
        TFNombre.setText("");
        TFDireccion.setText("");
        TFTelefonoCel.setText("");
        TFTelefono.setText("");
        TFCiudad.setText("");
        TFClave.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedico = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFTelefonoCel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFCiudad = new javax.swing.JTextField();
        BNuevo = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        TFBuscador = new org.jdesktop.swingx.JXSearchField();
        TFDireccion = new javax.swing.JTextField();
        CBCargo = new javax.swing.JComboBox<>();
        CBGrupo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medicos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        TablaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave:", "Cargo:", "Nombre:", "Dirección:", "Télefono:"
            }
        ));
        TablaMedico.setRowHeight(25);
        TablaMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedico);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 880, 240));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 26));

        TFNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 360, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("<-Busque por Nombre o seleccione por Cargo->:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 310, 26));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dirección:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 26));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Celular:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 50, 26));

        TFTelefonoCel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFTelefonoCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTelefonoCelActionPerformed(evt);
            }
        });
        TFTelefonoCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoCelKeyTyped(evt);
            }
        });
        getContentPane().add(TFTelefonoCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 360, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 26));

        TFTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTelefonoActionPerformed(evt);
            }
        });
        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(TFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 360, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ciudad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 26));

        TFCiudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFCiudadKeyPressed(evt);
            }
        });
        getContentPane().add(TFCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 360, -1));

        BNuevo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        BNuevo.setText("Nuevo");
        BNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 132, 36));

        BModificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BModificar.setText("Modificar");
        BModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 132, 36));

        BEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar.setText("Eliminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 132, 36));

        BCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 132, 36));

        TFBuscador.setText("");
        TFBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBuscadorActionPerformed(evt);
            }
        });
        getContentPane().add(TFBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 350, -1));

        TFDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(TFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 360, -1));

        CBCargo.setMaximumRowCount(10);
        CBCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Quimico", "Medico" }));
        CBCargo.setToolTipText("");
        CBCargo.setAutoscrolls(true);
        CBCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCargoActionPerformed(evt);
            }
        });
        getContentPane().add(CBCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 360, -1));

        CBGrupo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CBGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Medico", "Quimico" }));
        CBGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(CBGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cargo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 50, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Celular:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 50, 26));
        getContentPane().add(TFClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicoMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.buscarMedicos(TablaMedico, TFClave, TFNombre, CBCargo, TFDireccion, TFTelefonoCel, TFTelefono, TFCiudad);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TablaMedicoMouseClicked

    private void TFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreActionPerformed
        CBCargo.requestFocus();
    }//GEN-LAST:event_TFNombreActionPerformed

    private void TFTelefonoCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTelefonoCelActionPerformed
        TFTelefono.requestFocus();
    }//GEN-LAST:event_TFTelefonoCelActionPerformed

    private void TFTelefonoCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoCelKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (TFTelefonoCel.getText().length() >= 10) {
            JOptionPane.showMessageDialog(this, "Ingrese su numero telefonico correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFTelefonoCelKeyTyped

    private void TFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTelefonoActionPerformed
        TFCiudad.requestFocus();
    }//GEN-LAST:event_TFTelefonoActionPerformed

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (TFTelefono.getText().length() >= 10) {
            JOptionPane.showMessageDialog(this, "Ingrese su numero telefonico correcto");
            evt.consume();
        }
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void TFCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCiudadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BNuevo.doClick();
        }
    }//GEN-LAST:event_TFCiudadKeyPressed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        if (TFNombre.getText().isEmpty()
                || TFDireccion.getText().isEmpty()
                || TFTelefonoCel.getText().isEmpty()
                || TFTelefono.getText().isEmpty()
                || TFCiudad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llene los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            ConexionBDV cnx = new ConexionBDV();
            String Clave = TFClave.getText();
            String Cargo = CBCargo.getSelectedItem().toString();
            String Nombre = TFNombre.getText();
            String Direccion = TFDireccion.getText();
            String TelefonoCel = TFTelefonoCel.getText();
            String Telefono = TFTelefono.getText();
            String Ciudad = TFCiudad.getText();

            String consulta = "INSERT INTO TMedicos "
                    + "VALUES (null,"
                    + "'" + Cargo + "',"
                    + "'" + Nombre + "',"
                    + "'" + Direccion + "',"
                    + "'" + TelefonoCel + "',"
                    + "'" + Telefono + "',"
                    + "'" + Ciudad + "')";
            System.out.println(consulta);
            cnx.ejecutarConsultas(consulta);
            cnx.mostrarMedicos(TablaMedico);
            CBCargo.setSelectedItem("Cargo");
            limpiar();
            BModificar.setEnabled(true);
            cnx.cerrarConexiones();
        }

    }//GEN-LAST:event_BNuevoActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        String Clave1 = TFClave.getText();

        if (Clave1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un especialista antes");
        } else {

            ConexionBDV cnx = new ConexionBDV();
            String Clave = TFClave.getText();
            String Cargo = CBCargo.getSelectedItem().toString();
            String Nombre = TFNombre.getText();
            String Direccion = TFDireccion.getText();
            String TelefonoCel = TFTelefonoCel.getText();
            String Telefono = TFTelefono.getText();
            String Ciudad = TFCiudad.getText();

            String consulta = "UPDATE TMedicos SET " + "Cargo= '" + Cargo + "' , Nombre='" + Nombre + "' , Direccion='" + Direccion + "' , TelefonoCel='" + TelefonoCel + "',Telefono='" + Telefono + "' , Ciudad='" + Ciudad + "' WHERE Clave =" + Clave;
            System.out.println(consulta);
            cnx.ejecutarConsultas(consulta);
            cnx.mostrarMedicos(TablaMedico);
            CBCargo.setSelectedItem("Cargo");
            limpiar();
            cnx.cerrarConexiones();
        }
    }//GEN-LAST:event_BModificarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        String Clave1 = TFClave.getText();

        if (Clave1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un especialista antes");
        } else {

            int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar el registro?");
            if (respuesta == JOptionPane.YES_OPTION) {
                ConexionBDV cnx = new ConexionBDV();
                cnx.borrarMedicos(TFClave.getText());
                cnx.mostrarMedicos(TablaMedico);
                CBCargo.setSelectedItem("Cargo");
                limpiar();
                cnx.cerrarConexiones();
            } else {
                limpiar();
            }
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        CBCargo.setSelectedItem("Cargo");
        limpiar();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void TFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDireccionActionPerformed
        TFTelefonoCel.requestFocus();
    }//GEN-LAST:event_TFDireccionActionPerformed

    private void TFBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBuscadorActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarDatosParaMedicosBuscador(TablaMedico, TFBuscador);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TFBuscadorActionPerformed

    private void CBCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCargoActionPerformed

    private void CBGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGrupoActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        String Datos = (String) CBGrupo.getSelectedItem();
        if (Datos.equals("Medico")) {
            cnx.cargarMedicosCombo(TablaMedico, Datos);
        } else if (Datos.equals("Quimico")) {
            cnx.cargarMedicosCombo(TablaMedico, Datos);
        } else if (Datos.equals("Todos")) {
            MostrarMedicos();
        }

    }//GEN-LAST:event_CBGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Medicos dialog = new Medicos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JComboBox<String> CBCargo;
    private javax.swing.JComboBox<String> CBGrupo;
    private org.jdesktop.swingx.JXSearchField TFBuscador;
    private javax.swing.JTextField TFCiudad;
    private javax.swing.JTextField TFClave;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFTelefonoCel;
    private javax.swing.JTable TablaMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
