
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fernando Gonzalez
 */
public class ModificarConsulta extends javax.swing.JDialog {

    public ModificarConsulta(java.awt.Frame parent, boolean modal, String clave, String nombre, String Fecha) {
        super(parent, modal);
        initComponents();
        TFPaciente.setText(clave);
        TFNombre.setText(nombre);
        TFFFecha.setText(Fecha);
        TFNombre.setEnabled(false);
        TFFFecha.setEnabled(false);
        setLocationRelativeTo(this);
        ConexionBDV cnx = new ConexionBDV();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RUsuario = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        RResultado = new javax.swing.JRadioButton();
        BSalir = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        TFNombre = new javax.swing.JTextField();
        TFFFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        TFPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de los analisis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MODIFICAR ESTADO DE LA CONSULTA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 34));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Examenes realizados:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, -1));

        RUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        RUsuario.setForeground(new java.awt.Color(255, 255, 255));
        RUsuario.setText("Listo");
        RUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(RUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Resultados listos:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, -1));

        RResultado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        RResultado.setForeground(new java.awt.Color(255, 255, 255));
        RResultado.setText("Listo");
        RResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(RResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 140, 50));

        BSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BSalir.setText("Regresar");
        BSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BSalirMouseClicked(evt);
            }
        });
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 51));

        BActualizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BActualizar.setText("Actualizar");
        BActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BActualizarMouseClicked(evt);
            }
        });
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 130, 51));

        TFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, -1));

        TFFFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFFFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFFFechaActionPerformed(evt);
            }
        });
        getContentPane().add(TFFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha Consulta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, 45));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));
        getContentPane().add(TFPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSalirMouseClicked
        Consultas fa = new Consultas(null, true);
        fa.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BSalirMouseClicked

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSalirActionPerformed

    private void BActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BActualizarMouseClicked
        ConexionBDV cnx = new ConexionBDV();

        String Estado = RUsuario.getText().split("-")[0];
        String Resultado = RResultado.isSelected() ? RResultado.getText().split("-")[0] : ""; // Se selecciona el valor de Resultado solo si está seleccionado
        String Clave = TFPaciente.getText();

        String query = "UPDATE tcita SET Estado = '" + Estado + "'";
        if (!Resultado.isEmpty()) { // Si Resultado no está vacío (se seleccionó), se agrega a la consulta
            query += ", Resultados = '" + Resultado + "'";
        }
        query += " WHERE NoCita = " + Clave;

        System.out.println(query);
        cnx.ejecutarConsultas(query);
         this.dispose();
        Consultas fa = new Consultas(null, true);
        fa.setVisible(true);    
        cnx.cerrarConexiones();
 


    }//GEN-LAST:event_BActualizarMouseClicked

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActualizarActionPerformed

    private void TFFFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFFFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModificarConsulta dialog = new ModificarConsulta(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BSalir;
    private javax.swing.JRadioButton RResultado;
    private javax.swing.JRadioButton RUsuario;
    private javax.swing.JTextField TFFFecha;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
