import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Fernando Gonzalez
 */
public class ModificarCita extends javax.swing.JDialog {

    JSpinner.DateEditor editor;
    
    public ModificarCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        ConexionBDV cnx = new ConexionBDV();
        MostrarCita();
        cnx.llenarcomboPacientes(CBUsuario);
        cnx.llenarcomboMedicos(CBMedico);
        cnx.llenarcomboNombreP(CBNombreP);
        cnx.llenarcomboGYP(CBExamen);
        TFNoCita.setEnabled(false);
    }
    public void MostrarCita() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarCitas(TPrincipal);
        cnx.cerrarConexiones();
    }
    public String obtenerFecha() {

        int annio = SPFecha.getCalendar().get(Calendar.YEAR);
        int mesSelect = SPFecha.getCalendar().get(Calendar.MONTH) + 1;
        int diaSelect = SPFecha.getCalendar().get(Calendar.DAY_OF_MONTH);

        String mes = mesSelect + "";

        if (mesSelect <= 9) {
            mes = "0" + mesSelect;
        }
        String dia = diaSelect + "";
        if (diaSelect <= 9) {
            dia = "0" + diaSelect;
        }

        String fechaseleccionada = annio + "-" + mes + "-" + dia;
        return fechaseleccionada;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        CBNombreP = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        SPFecha = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        CBMedico = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        CBUsuario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        CBExamen = new javax.swing.JComboBox<>();
        BModificar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        CBResultados = new javax.swing.JComboBox<>();
        PExaIndividuales = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPrincipal = new javax.swing.JTable();
        CBEstado = new javax.swing.JComboBox<>();
        TFHora = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TFNoCita = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CBNombreP1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        SPFecha1 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        CBMedico1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        CBUsuario1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        CBExamen1 = new javax.swing.JComboBox<>();
        BModificar1 = new javax.swing.JButton();
        BEliminar1 = new javax.swing.JButton();
        BCancelar1 = new javax.swing.JButton();
        CBResultados1 = new javax.swing.JComboBox<>();
        PExaIndividuales1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPrincipal1 = new javax.swing.JTable();
        CBEstado1 = new javax.swing.JComboBox<>();
        TFHora1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TFNoCita1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");

        CBNombreP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CBNombreP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente" }));
        CBNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNombrePActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha:");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("No. Medico:");

        CBMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico" }));
        CBMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMedicoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("NoPaciente:");

        CBUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente" }));
        CBUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUsuarioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Examen:");

        CBExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Examen" }));
        CBExamen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExamenActionPerformed(evt);
            }
        });

        BModificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BModificar.setText("Modificar");
        BModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        BEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar.setText("Eiminar");
        BEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminarMouseClicked(evt);
            }
        });
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        BCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        CBResultados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso" }));
        CBResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PExaIndividuales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Citas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        TPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Telefono", "Fecha", "Hora", "Realizar Examen", "Estado", "Resultados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TPrincipal);

        javax.swing.GroupLayout PExaIndividualesLayout = new javax.swing.GroupLayout(PExaIndividuales);
        PExaIndividuales.setLayout(PExaIndividualesLayout);
        PExaIndividualesLayout.setHorizontalGroup(
            PExaIndividualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PExaIndividualesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PExaIndividualesLayout.setVerticalGroup(
            PExaIndividualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExaIndividualesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso" }));
        CBEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TFHora.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Hora:");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NoCita:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 17, -1, 26));

        CBNombreP1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CBNombreP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente" }));
        CBNombreP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNombreP1ActionPerformed(evt);
            }
        });
        getContentPane().add(CBNombreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 17, 470, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 59, -1, 26));
        getContentPane().add(SPFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("No. Medico:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        CBMedico1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico" }));
        CBMedico1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBMedico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMedico1ActionPerformed(evt);
            }
        });
        getContentPane().add(CBMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("NoPaciente:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 57, -1, 26));

        CBUsuario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente" }));
        CBUsuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(CBUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 57, 220, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Examen:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 26));

        CBExamen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Examen" }));
        CBExamen1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBExamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExamen1ActionPerformed(evt);
            }
        });
        getContentPane().add(CBExamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 110, 220, -1));

        BModificar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BModificar1.setText("Modificar");
        BModificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 168, 132, 36));

        BEliminar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BEliminar1.setText("Eiminar");
        BEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminar1MouseClicked(evt);
            }
        });
        BEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 170, 160, 30));

        BCancelar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        BCancelar1.setText("Cancelar");
        BCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 168, 132, 36));

        CBResultados1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso" }));
        CBResultados1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(CBResultados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 130, 30));

        PExaIndividuales1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Citas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        TPrincipal1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Telefono", "Fecha", "Hora", "Realizar Examen", "Estado", "Resultados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPrincipal1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TPrincipal1);

        javax.swing.GroupLayout PExaIndividuales1Layout = new javax.swing.GroupLayout(PExaIndividuales1);
        PExaIndividuales1.setLayout(PExaIndividuales1Layout);
        PExaIndividuales1Layout.setHorizontalGroup(
            PExaIndividuales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PExaIndividuales1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PExaIndividuales1Layout.setVerticalGroup(
            PExaIndividuales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExaIndividuales1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PExaIndividuales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        CBEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso" }));
        CBEstado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(CBEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 55, 130, 30));

        TFHora1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        getContentPane().add(TFHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 130, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Hora:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, 26));
        getContentPane().add(TFNoCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 112, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NoCita:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio23.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio23.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 570, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBNombrePActionPerformed

    private void CBMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMedicoActionPerformed

    private void CBUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBUsuarioActionPerformed

    private void CBExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBExamenActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed

        ConexionBDV cnx = new ConexionBDV();
        String Fecha = obtenerFecha();
        String NoCita = TFNoCita.getText();
        String Hora = TFHora.getText();
        String Examen = CBExamen.getSelectedItem().toString().split("-")[0];
        String Estado = CBEstado.getSelectedItem().toString().split("-")[0];
        String Resultados = CBResultados.getSelectedItem().toString().split("-")[0];
        String NoPaciente = CBUsuario.getSelectedItem().toString().split("-")[0];
        String NoMedico = CBMedico.getSelectedItem().toString().split("-")[0];

        if (NoCita.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione la cita en la tabla");

        } else {

            String consulta = "UPDATE Tcita "
            + "SET Hora = '" + Hora + "', "
            + "Fecha = '" + Fecha + "', "
            + "ExamenRealizar = '" + Examen + "', "
            + "Estado = '" + Estado + "', "
            + "Resultados = '" + Resultados + "', "
            + "NoMedico = '" + NoMedico + "', "
            + "NoPaciente = '" + NoPaciente + "' "
            + "WHERE NoCita = " + NoCita;
            System.out.println(consulta);
            cnx.ejecutarConsultas(consulta);
            cnx.mostrarCitas(TPrincipal);
            TFHora.setText("");
            BModificar.setEnabled(true);
            cnx.cerrarConexiones();

        }
    }//GEN-LAST:event_BModificarActionPerformed

    private void BEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.borrarCitas(TFNoCita.getText());
        //  cnx.verPizzas(TPizzas);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminarMouseClicked

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.borrarCitas(TFNoCita.getText());
        //  cnx.verPizzas(TPizzas);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        // TFCargo.setText("");

        TFHora.setText("");
    }//GEN-LAST:event_BCancelarActionPerformed

    private void TPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPrincipalMouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.buscarCita(TPrincipal, TFNoCita);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TPrincipalMouseClicked

    private void CBNombreP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNombreP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBNombreP1ActionPerformed

    private void CBMedico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMedico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMedico1ActionPerformed

    private void CBUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBUsuario1ActionPerformed

    private void CBExamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBExamen1ActionPerformed

    private void BModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificar1ActionPerformed

        ConexionBDV cnx = new ConexionBDV();
        String Fecha = obtenerFecha();
        String NoCita = TFNoCita.getText();
        String Hora = TFHora.getText();
        String Examen = CBExamen.getSelectedItem().toString().split("-")[0];
        String Estado = CBEstado.getSelectedItem().toString().split("-")[0];
        String Resultados = CBResultados.getSelectedItem().toString().split("-")[0];
        String NoPaciente = CBUsuario.getSelectedItem().toString().split("-")[0];
        String NoMedico = CBMedico.getSelectedItem().toString().split("-")[0];

        if (NoCita.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione la cita en la tabla");

        } else {

            String consulta = "UPDATE Tcita "
            + "SET Hora = '" + Hora + "', "
            + "Fecha = '" + Fecha + "', "
            + "ExamenRealizar = '" + Examen + "', "
            + "Estado = '" + Estado + "', "
            + "Resultados = '" + Resultados + "', "
            + "NoMedico = '" + NoMedico + "', "
            + "NoPaciente = '" + NoPaciente + "' "
            + "WHERE NoCita = " + NoCita;
            System.out.println(consulta);
            cnx.ejecutarConsultas(consulta);
            cnx.mostrarCitas(TPrincipal);
            TFHora.setText("");
            BModificar.setEnabled(true);
            cnx.cerrarConexiones();

        }
    }//GEN-LAST:event_BModificar1ActionPerformed

    private void BEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminar1MouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.borrarCitas(TFNoCita.getText());
        //  cnx.verPizzas(TPizzas);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminar1MouseClicked

    private void BEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminar1ActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.borrarCitas(TFNoCita.getText());
        //  cnx.verPizzas(TPizzas);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_BEliminar1ActionPerformed

    private void BCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelar1ActionPerformed
        // TFCargo.setText("");

        TFHora.setText("");
    }//GEN-LAST:event_BCancelar1ActionPerformed

    private void TPrincipal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPrincipal1MouseClicked
        ConexionBDV cnx = new ConexionBDV();
        cnx.buscarCita(TPrincipal, TFNoCita);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TPrincipal1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarCita dialog = new ModificarCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BCancelar1;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BEliminar1;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BModificar1;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBEstado1;
    private javax.swing.JComboBox<String> CBExamen;
    private javax.swing.JComboBox<String> CBExamen1;
    private javax.swing.JComboBox<String> CBMedico;
    private javax.swing.JComboBox<String> CBMedico1;
    private javax.swing.JComboBox<String> CBNombreP;
    private javax.swing.JComboBox<String> CBNombreP1;
    private javax.swing.JComboBox<String> CBResultados;
    private javax.swing.JComboBox<String> CBResultados1;
    private javax.swing.JComboBox<String> CBUsuario;
    private javax.swing.JComboBox<String> CBUsuario1;
    private javax.swing.JPanel PExaIndividuales;
    private javax.swing.JPanel PExaIndividuales1;
    private com.toedter.calendar.JDateChooser SPFecha;
    private com.toedter.calendar.JDateChooser SPFecha1;
    private javax.swing.JTextField TFHora;
    private javax.swing.JTextField TFHora1;
    private javax.swing.JTextField TFNoCita;
    private javax.swing.JTextField TFNoCita1;
    private javax.swing.JTable TPrincipal;
    private javax.swing.JTable TPrincipal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
