
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fernando Gonzalez
 */
public class Resultados extends javax.swing.JDialog {

    /**
     * Creates new form Resultados1
     */
    public Resultados(java.awt.Frame parent, boolean modal, String Nombre, String Fecha) {
        super(parent, modal);
        ImageIcon icono = new ImageIcon(getClass().getResource("imagenes\\icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        TFBuscador1.setText(Nombre);
        TFFecha.setText(Fecha);
        TFBuscador1.setEnabled(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        ConexionBDV cnx = new ConexionBDV();

    }

    public void MostrarTabla() {
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarCitaExamen(TDatos);
        cnx.cerrarConexiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BResultados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDatos = new javax.swing.JTable();
        TFBuscador1 = new org.jdesktop.swingx.JXSearchField();
        jLabel3 = new javax.swing.JLabel();
        TFPaciente1 = new javax.swing.JTextField();
        TFCitaExamen1 = new javax.swing.JTextField();
        TFCita1 = new javax.swing.JTextField();
        TFExamen1 = new javax.swing.JTextField();
        TFParametro1 = new javax.swing.JTextField();
        TFNombreE = new javax.swing.JTextField();
        TFNombreP = new javax.swing.JTextField();
        TFFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RESULTADOS ANALISIS DEL PACIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 280, -1));

        BResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.gif"))); // NOI18N
        BResultados.setText("Ingresar");
        BResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResultadosActionPerformed(evt);
            }
        });
        getContentPane().add(BResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 120, 70));

        TDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Paciente", "CitaExamen", "Cita", "Examen", "Parametros", "NoMedico", "noExamen", "NoPaciente", "Ingrese el resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TDatos.setRowHeight(25);
        TDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TDatos);
        if (TDatos.getColumnModel().getColumnCount() > 0) {
            TDatos.getColumnModel().getColumn(1).setMinWidth(0);
            TDatos.getColumnModel().getColumn(1).setPreferredWidth(0);
            TDatos.getColumnModel().getColumn(1).setMaxWidth(0);
            TDatos.getColumnModel().getColumn(4).setMinWidth(0);
            TDatos.getColumnModel().getColumn(4).setPreferredWidth(0);
            TDatos.getColumnModel().getColumn(4).setMaxWidth(0);
            TDatos.getColumnModel().getColumn(5).setMinWidth(0);
            TDatos.getColumnModel().getColumn(5).setPreferredWidth(0);
            TDatos.getColumnModel().getColumn(5).setMaxWidth(0);
            TDatos.getColumnModel().getColumn(6).setMinWidth(0);
            TDatos.getColumnModel().getColumn(6).setPreferredWidth(0);
            TDatos.getColumnModel().getColumn(6).setMaxWidth(0);
            TDatos.getColumnModel().getColumn(7).setMinWidth(0);
            TDatos.getColumnModel().getColumn(7).setPreferredWidth(0);
            TDatos.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 730, 250));

        TFBuscador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFBuscador1.setText("");
        TFBuscador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBuscador1ActionPerformed(evt);
            }
        });
        getContentPane().add(TFBuscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 290, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteframe.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 450));
        getContentPane().add(TFPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 70, -1));
        getContentPane().add(TFCitaExamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 60, -1));
        getContentPane().add(TFCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 60, -1));

        TFExamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFExamen1ActionPerformed(evt);
            }
        });
        getContentPane().add(TFExamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 80, -1));
        getContentPane().add(TFParametro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 80, -1));
        getContentPane().add(TFNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, -1));
        getContentPane().add(TFNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, -1));
        getContentPane().add(TFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResultadosActionPerformed

        ConexionBDV cnx = new ConexionBDV();
        DefaultTableModel modeloT = (DefaultTableModel) TDatos.getModel();

        boolean columna6Presente = false;
        String Resultado = null;
        String Examen = null;
        String Parametro = null;
        String CitaExamen = null;
        String Cita = null;
        String NoPaciente = null;
        String NoMedico = null;

// Recorrer todas las filas de la tabla
        for (int i = 0; i < modeloT.getRowCount(); i++) {
            if (modeloT.getValueAt(i, 5) != null) {
                columna6Presente = true;
                NoPaciente = modeloT.getValueAt(i, 7).toString();
                CitaExamen = modeloT.getValueAt(i, 1).toString();
                Cita = modeloT.getValueAt(i, 2).toString();
                Examen = modeloT.getValueAt(i, 6).toString();
                Parametro = modeloT.getValueAt(i, 4).toString();
                NoMedico = modeloT.getValueAt(i, 5).toString();
                Resultado = modeloT.getValueAt(i, 8).toString();

                String consulta = "INSERT INTO resultadosparametro "
                        + "VALUES (null,'" + Resultado + "',"
                        + "'" + Parametro + "',"
                        + "'" + CitaExamen + "',"
                        + "'" + Examen + "',"
                        + "'" + Cita + "',"
                        + "'" + NoMedico + "',"
                        + "'" + NoPaciente + "')";
                System.out.println(consulta);
                BResultados.setEnabled(false);
                cnx.ejecutarConsultas(consulta);
            }
        }

        if (columna6Presente) {
            JOptionPane.showMessageDialog(null, "Los resultados se han ingresado correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor antes de guardar", "Error", JOptionPane.ERROR_MESSAGE);
        }

        cnx.cerrarConexiones();


    }//GEN-LAST:event_BResultadosActionPerformed

    private void TDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TDatosMouseClicked
        TDatos.clearSelection();
    }//GEN-LAST:event_TDatosMouseClicked

    private void TFExamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFExamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFExamen1ActionPerformed

    private void TFBuscador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBuscador1ActionPerformed
        ConexionBDV cnx = new ConexionBDV();
        cnx.mostrarDatosParaResultadosBuscador(TDatos, TFBuscador1, TFFecha);
        cnx.cerrarConexiones();
    }//GEN-LAST:event_TFBuscador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Resultados dialog = new Resultados(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BResultados;
    private javax.swing.JTable TDatos;
    private org.jdesktop.swingx.JXSearchField TFBuscador1;
    private javax.swing.JTextField TFCita1;
    private javax.swing.JTextField TFCitaExamen1;
    private javax.swing.JTextField TFExamen1;
    private javax.swing.JTextField TFFecha;
    private javax.swing.JTextField TFNombreE;
    private javax.swing.JTextField TFNombreP;
    private javax.swing.JTextField TFPaciente1;
    private javax.swing.JTextField TFParametro1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
